### ISSUE TITLE
Potential undesirable results

### ISSUE THREAD

**Issue by sachaw** [matthewdias/Kitsu.bundle#6]
Upon plex recently mixing up old cache items and the new ones after being renamed, someone also pointed out a potential bug in the agent, so you may want to have a look (I have yet to experience this yet though, as I name everything as it appears in kitsu)
https://www.reddit.com/r/PleX/comments/c8nkl9/plex_just_randomly_started_incorrectly_mapping/eso6udt?utm_source=share&utm_medium=web2x

**Comment by matthewdias** [comment]
Yeah, this isn't really a bug, but a suboptimal method for searching. There isn't really a perfect way to do it which is why I recommend naming stuff the same way Kitsu has it. Tho I think the Kitsu search usually does a good job returning what you want for the first result. And if it doesn't, you can always go manually fix the match.
